### PR TITLE
upgrade tqdm 4.14 -> 4.50.2 to support python 3.9

### LINKED ISSUE #167: “Downloading the first original photo or video” then stops
```
15macbookpro@15Macbookpro Pictures % icloudpd --directory /Volumes/Media/Pictures --username rpandula@uh.edu --password ******                                         
2020-10-07 14:06:12 DEBUG    Authenticating...
2020-10-07 14:06:19 DEBUG    Looking up all photos and videos from album All Photos...
2020-10-07 14:06:20 INFO     Downloading the first original photo or video to /Volumes/Media/Pictures/ ...
100%|#################################################################################| 1/1 [00:00<00:00,  1.62it/s]
2020-10-07 14:06:21 INFO     All photos have been downloaded!

```

I have about 40,000 photos+videos since 2010 on my iCloud Photo Library. Not sure why its stopping after downloading one random picture from 2019. Probably a simple config I’m missing, but i can’t seem to figure it out. 

I even tried telling it just download the most recent 40k pics

```
15macbookpro@15Macbookpro Pictures % icloudpd --directory /Volumes/Media/Pictures --username rpandula@uh.edu --password **** --set-exif-datetime --recent 40000 
2020-10-07 13:57:41 DEBUG    Authenticating...
2020-10-07 13:57:46 DEBUG    Looking up all photos and videos from album All Photos...
2020-10-07 13:57:46 INFO     Downloading 40000 original photos and videos to /Volumes/Media/Pictures/ ...
  0%|                                                                           | 1/40000 [00:00<3:30:16,  3.17it/s]
2020-10-07 13:57:47 INFO     All photos have been downloaded!

```

And I got the same issue. Any help would be much appreciated it

### PR DESCRIPTION
**Pull request by AndreyNikiforov**
fixes #167

### CODE REVIEW

**Comment by menkej** [comment]
I was thinking about the same - lib upgrade. Some of the used libs are rather old already. On Mac it see no negative side-effects with an upgraded tqdm yet. I did not try it on Windows (yet), as I don't have a python install there as of now.

Something I noticed - wich is probably not related to this change - is that the unit-tests don't run on my machine any more. Do they work on your installation?

```
➜  icloud_photos_downloader git:(master) ✗ scripts/run_all_checks
Running pylint for Python 3...

-------------------------------------------------------------------
Your code has been rated at 10.00/10 (previous run: 9.98/10, +0.02)

Running tests with Python 3... (HTML coverage report)
============================================================ test session starts ============================================================
platform darwin -- Python 3.8.5, pytest-3.6.4, py-1.9.0, pluggy-0.7.1
rootdir: /Users/joerg/Desktop/Entwicklung/python/icloud_photos_downloader, inifile: pytest.ini
plugins: cov-2.5.1
collected 40 items

tests/test_authentication.py ....                                                                                                     [ 10%]
tests/test_autodelete_photos.py .                                                                                                     [ 12%]
tests/test_cli.py ....                                                                                                                [ 22%]
tests/test_download_photos.py ....F......
```
The run hangs for ages in this state and at least one test is failing.

cheers
Jörg

**Comment by AndreyNikiforov** [comment]
@menkej I have issues with unit test too (Windows). I did not registered at what point they started to fail though. `py.test --cov=icloudpd --timeout=3 --cov-report term-missing` -- adding timeout helped resolving hanging tests. Running `docker build .`, which executes tests, gives consistent results of all tests passing.

**Comment by menkej** [comment]
Thanks for the hint with the timeout, Andrey! I just noticed that requirements-test.txt was updated, too. So now I can just add a timeout. 

Regarding the failing tests I did not look into them yet. Just for one I noticed that the file that should be downloaded seems not to be in the cached iCloud response any more, so maybe just the cached iCloud-data was changed without updating all tests? Just a wild guess. I did not really have contact with this for about a year.

**Review by menkej — APPROVED** [review]
I was thinking about trying the latest version of that lib, too. I didn't test with python 3.9. I'm still with 3.8.5 but I could not see any negative side effects. I'm good to go with this.

Maybe we should update the requirements (3rd party libs) in general somewhen, as we have ditched python2 now and some of the libs are rather old (or forked)...

**Comment by AndreyNikiforov** [comment]
@menkej good idea to bump up requirements. Are there any known features that such bumping can bring?

**Pull request merged**
