### PR TITLE
add Chinese base path test; refactor tests for multi platform support

### PR DESCRIPTION
**Pull request by AndreyNikiforov**
writing tests to confirm compatibility of the platform with Chinese chars for #175

### CODE REVIEW

**Review by menkej — APPROVED** [review]
Great work and a long diff to scan over! ;-)
Didn't know about normpath-method. Makes totally sense!
I can't test this on Windows right now. I assume os.path.join() handles slash vs backlash  correctly... 

Thinking about the logger issues we're having (also with a pull request) I'm more and more thinking about putting this program into a more object oriented (classes based) structure. So we could use just one logger instance for all... Nothing really todo with this change, but on my mind...

**Comment by AndreyNikiforov** [comment]
> I can't test this on Windows right now. I assume os.path.join() handles slash vs backlash correctly...

Yes, you are correct, join() handles proper slashes

**Comment by ndbroadbent** [comment]
Thanks for all the great work so far @AndreyNikiforov and @menkej! Please ping me whenever you would like to release a new version and I'm happy to take a look.

I'd also be happy to hand this over to you guys if you wanted to manage some of the releases

**Comment by AndreyNikiforov** [comment]
> I'd also be happy to hand this over to you guys if you wanted to manage some of the releases

Just created #181 to address/improve that situation

**Pull request merged**
