### PR TITLE
new commandline parameters fixes #106

### LINKED ISSUE #106: Download specific album
First, super thanks for an awesome tool. I'm using it and it's amazing!

I would like to have the option to download a specific album by his name. For example,  I want to download all my favorite photos.

Thanks in advance.
Ran

### PR DESCRIPTION
**Pull request by menkej**
I added two new parameters:

--list-albums (list all albums)
-a, --album (select the album to be downloaded)

With this it is possible to download a specific album only. I use this for my screensaver album. "All Photos" is still the default. I also made "directory" an option, so that it is not mandatory any more. I did not add a default target directory but I guess "." can be a valid default. What do you think about this?

### CODE REVIEW

**Comment by menkej** [comment]
Ok, maybe I should also have a look at the tests...

**Comment by menkej** [comment]
> Ok, maybe I should also have a look at the tests...

**Comment by menkej** [comment]
It seems like the user used for running the test-cases is active. Is it so, @ndbroadbent ? This influences the creation of test cases...

**Comment by ndbroadbent** [comment]
> It seems like the user used for running the test-cases is active. Is it so, @ndbroadbent ? This influences the creation of test cases...

Hi, yes I created the test cases by using my own iCloud account, but then I recorded all of the API responses with VCR, so they can be run offline, on CI, etc.

It might be tricky to add new test cases for VCR, but you could do the same thing by setting up a VCR cassette and entering your own iCloud password, and them making sure to remove the password from the recorded responses.

**Comment by ndbroadbent** [comment]
Hi @menkej, thanks very much for all your work! I've fixed the remaining issue, will merge your changes into master, and release this under version: 1.4.4. Thanks!

**Pull request closed without merging**
